apps/users/urls.py
from django.contrib.auth.views import logout_then_login
from django.urls import path

from .views import login_view, user_settings, change_password

app_name = 'users'

urlpatterns = [
    path("login/", login_view, name='login'),
    path("logout/", logout_then_login, name='logout'),
    path("user/settings/", user_settings, name='user_settings'),
    path("user/change_password/", change_password, name='change_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.core.views import index, send_test_email, store_in_cache

urlpatterns = [
    path("", index),
    path("", include('apps.users.urls')),
    path('components/', include('components.urls')),
    path("send-email/", send_test_email),
    path("store-cache/", store_in_cache),
    path("admin/", admin.site.urls),
    path("transactions/", include('apps.transactions.urls')),
    path("accounts/", include('apps.accounts.urls')),
    path("goals/", include('apps.goals.urls')),
    path("debts/", include('apps.debts.urls')),
    path('webpush/', include('webpush.urls'))

]

apps/users/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def save(self, *args, **kwargs):
        if not self.username:
            self.username = self.email
        return super(User, self).save(*args, **kwargs)

    @property
    def initials(self):
        if self.first_name and self.last_name:
            return f"{self.first_name[0]}{self.last_name[0]}"
        return "?"

apps/users/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form

from apps.users.models import User


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class UserChangePasswordForm(Form):
    password = forms.CharField(widget=forms.PasswordInput)
    repeat_password = forms.CharField(widget=forms.PasswordInput)

    def clean_password(self):
        validate_password(self.data['password'])
        return self.data['password']

    def clean_repeat_password(self):
        if self.data['password'] != self.data['repeat_password']:
            raise ValidationError('La contraseña no coincide')

    def clean(self):
        if self.data['password'] != self.data['repeat_password']:
            raise ValidationError('Deben coincidir las contraseñas')
        return self.cleaned_data

apps/users/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from apps.users.forms import UserUpdateForm, UserChangePasswordForm


# Create your views here.
def login_view(request):
    if request.method == "GET":
        return render(request, "pages/users/login.html")
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = authenticate(request, username=username, password=password)
    if user:
        login(request, user)
    return redirect(request.GET.get("next") or "/")


@login_required()
def user_settings(request):
    if request.method == "POST":
        user_update_form = UserUpdateForm(data=request.POST, instance=request.user)
        if user_update_form.is_valid():
            user_update_form.save()
            messages.add_message(request, messages.SUCCESS, "Guardado con éxito")
        else:
            messages.add_message(request, messages.ERROR, user_update_form.errors)
    else:
        user_update_form = UserUpdateForm(instance=request.user)
    context = {
        'user_update_form': user_update_form,
        'change_password_form': UserChangePasswordForm()
    }
    return render(request, "pages/users/settings.html", context)


@login_required()
def change_password(request):
    if request.method == "POST":
        change_password_form = UserChangePasswordForm(data=request.POST)
        if change_password_form.is_valid():
            request.user.set_password(change_password_form.cleaned_data['password'])
            request.user.save()
        else:
            messages.add_message(request, messages.ERROR, change_password_form.non_field_errors())
    else:
        change_password_form = UserChangePasswordForm()
    context = {
        'user_update_form': UserUpdateForm(instance=request.user),
        'change_password_form': change_password_form
    }
    return render(request, "pages/users/settings.html", context)

templates/pages/users/login.html
{% extends 'pages/base.html' %}

{% block content %}
    <section class="bg-gray-50">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900">
                Mani
            </a>
            <div class="w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
                        Inicia sesión y controla tus gastos
                    </h1>
                    <form class="space-y-4 md:space-y-6" method="post" hx-boost="false">
                        {% csrf_token %}
                        <div>
                            <label for="username" class="block mb-2 text-sm font-medium text-gray-900">Nombre de
                                usuario</label>
                            <input type="text" name="username" id="username"
                                   class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5"
                                   placeholder="Usuario" required="">
                        </div>
                        <div>
                            <label for="password"
                                   class="block mb-2 text-sm font-medium text-gray-900">Contraseña</label>
                            <input type="password" name="password" id="password" placeholder="••••••••"
                                   class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5"
                                   required="">
                        </div>
                        <button type="submit"
                                class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                            Iniciar sesión
                        </button>
                        <p class="text-sm font-light text-gray-500">
                            Si aún no tienes cuenta, solicítala a un administrador
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {#  <main>#}
    {#    <div class="container-fluid">#}
    {#      <div class="row">#}
    {#        <div class="col-sm-6 login-section-wrapper">#}
    {#          <div class="brand-wrapper">#}
    {#             <h1> Mani</h1>#}
    {#             <h3>Controla tus gastos</h3>#}
    {#          </div>#}
    {#          <div class="login-wrapper my-auto">#}
    {#            <h1 class="login-title">Log in</h1>#}
    {#            <form method="post" hx-boost="false">#}
    {#                {% csrf_token %}#}
    {#              <div class="form-group">#}
    {#                <label for="email">Email</label>#}
    {#                <input type="text" name="username" id="email" class="form-control" placeholder="username">#}
    {#              </div>#}
    {#              <div class="form-group mb-4">#}
    {#                <label for="password">Password</label>#}
    {#                <input type="password" name="password" id="password" class="form-control" placeholder="enter your passsword">#}
    {#              </div>#}
    {#                <button class="btn btn-block login-btn" type="submit">Login</button>#}
    {#            </form>#}
    {#          </div>#}
    {#        </div>#}
    {#        <div class="col-sm-6 px-0 d-none d-sm-block">#}
    {#          <img src="https://demo.bootstrapdash.com/login-template-free-1/assets/images/login.jpg" alt="login image" class="login-img">#}
    {#        </div>#}
    {#      </div>#}
    {#    </div>#}
    {#  </main>#}
    {#    <main class="form-signin">#}
    {#        <form method="post">#}
    {#            {% csrf_token %}#}
    {##}
    {#            <h1 class="h3 mb-3 fw-normal">Mani</h1>#}
    {##}
    {#            <div class="form-floating">#}
    {#                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="usuario">#}
    {#                <label for="floatingInput">Usuario</label>#}
    {#            </div>#}
    {#            <div class="form-floating">#}
    {#                <input type="password" name="password" class="form-control" id="floatingPassword"#}
    {#                       placeholder="contraseña">#}
    {#                <label for="floatingPassword">Contraseña</label>#}
    {#            </div>#}
    {##}
    {#            <div class="checkbox mb-3">#}
    {#                <label>#}
    {#                    <input type="checkbox" value="remember-me"> Remember me#}
    {#                </label>#}
    {#            </div>#}
    {#            <button class="w-100 btn btn-lg btn-blue" type="submit">Sign in</button>#}
    {#            <p class="mt-5 mb-3 text-muted">© 2017–2021</p>#}
    {#        </form>#}
    {#    </main>#}

{% endblock %}

templates/pages/users/settings.html
{% extends 'pages/base.html' %}

{% block content %}
    <div class="w-full py-2 bg-gray-100">
        <div class="px-8 py-4 mx-auto shadow-md bg-white rounded-md mb-4">
            <h2 class="text-2xl font-bold">Configuración</h2>

            <form hx-post="." hx-target="#page">
                <div class="grid grid-cols-2 gap-3 my-3">
                    <div>
                        {% include 'components/field.html' with field=user_update_form.first_name %}
                    </div>
                    <div>
                        {% include 'components/field.html' with field=user_update_form.last_name %}
                    </div>
                </div>
                {% include 'components/field.html' with field=user_update_form.email %}
                <div class="w-full flex justify-end mt-3">
                    <button class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-md text-sm px-5 py-2.5 me-2 mb-2"
                            type="submit">Actualizar
                    </button>
                </div>
            </form>
        </div>
        <div class="px-8 py-4 mx-auto shadow-md bg-white rounded-md">
            <h2 class="text-2xl font-bold">Cambiar contraseña</h2>

            <form hx-post="{% url 'users:change_password' %}" hx-target="#page">
                <div class="my-3">{% include 'components/field.html' with field=change_password_form.password %}</div>
                <div class="my-3">{% include 'components/field.html' with field=change_password_form.repeat_password %}</div>
                <div class="w-full flex justify-end mt-3">
                    <button class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-md text-sm px-5 py-2.5 me-2 mb-2"
                            type="submit">Cambiar contraseña
                    </button>
                </div>
            </form>

        </div>
    </div>
{% endblock %}